services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - ./linux/logrotate.d/app:/etc/logrotate.d/app
    ports:
      - "8000:8000"
    environment:
      - ENV=prod
    working_dir: /app
    command: sh -c "go build cmd/main.go && ./main"
    restart: always
    tty: true
